"""01_initial-db

Revision ID: 5553cb227535
Revises: 
Create Date: 2023-09-30 13:24:18.307907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5553cb227535'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_key'), 'urls', ['key'], unique=True)
    op.create_index(op.f('ix_urls_secret_key'), 'urls', ['secret_key'], unique=True)
    op.create_index(op.f('ix_urls_target_url'), 'urls', ['target_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_target_url'), table_name='urls')
    op.drop_index(op.f('ix_urls_secret_key'), table_name='urls')
    op.drop_index(op.f('ix_urls_key'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
